// src/components/input/wrap.vue3.vue
<template>
  <fl-input
    v-bind="{...props}"
    @update-model-value="emit('update:modelValue', $event.detail[0])"
    ref="compRef"
  ></fl-input>
</template>

<script lang="ts" setup>
import { ref, onMounted } from 'vue';
import './index';
import { PropsTypeV3, defaultPropsV3} from './utils.ts';

const props = withDefaults(defineProps<PropsTypeV3>(), defaultPropsV3);

const emit = defineEmits<{
  (e: 'update:modelValue', value: string | number): void
}>();

const compRef = ref();

onMounted(()=>{
  compRef.value?._onMounted?.();
})

defineExpose(
  new Proxy(
    {},
    {
      get(_, key) {
        return compRef.value?.[key];
      },
      has(_, key) {
        return key in (compRef.value || {});
      },
    }
  ),
)
</script>

<style lang="scss" scoped>

</style>

// src/components/input/wrap.react.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
import { ExposeTypeReact, PropsTypeReact } from './utils';
import './index';

export default forwardRef(function FlInput(props: PropsTypeReact, ref: any) {
  const ceInstance = useRef();

  useEffect(() => {
    ceInstance.current.modelValue = props.modelValue;
  }, [props.modelValue])

  useEffect(() => {
    ceInstance.current.addEventListener('update-model-value', (event: CustomEvent) => {
      props.onUpdateModelValue(...event.detail);
    })
  }, [props.onUpdateModelValue])

  useEffect(() => {
    ceInstance.current._onMounted?.();
  }, [])

  useImperativeHandle(ref, (): ExposeTypeReact => {
    return {
      focus() {
        ceInstance.current?.focus?.();
      },
    };
  }, []);
  
  return <>
    <fl-input
      {...props}
      ref={ceInstance}
    >
    </fl-input>
  </>
})
