// src/components/input/wrap.react.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef, type FC } from 'react';
import { ExposeTypeReact, PropsTypeReact } from './utils';
import './index';

export default forwardRef(function FlInput(props: PropsTypeReact, ref: any) {
  const ceInstance = useRef();

  useEffect(() => {
    ceInstance.current!.modelValue = props.modelValue;
  }, [props.modelValue])

  useEffect(() => {
    const fn = (event: CustomEvent) => {
      props.onUpdateModelValue(...event.detail);
    }
    ceInstance.current?.addEventListener('update-model-value', fn);
    return () => {
      ceInstance.current?.removeEventListener('update-model-value', fn);
    }
  }, [props.onUpdateModelValue])

  useEffect(() => {
    ceInstance.current?._onMounted?.();
  }, [])

  useImperativeHandle(ref, (): ExposeTypeReact => {
    return {
      focus() {
        ceInstance.current?.focus?.();
      },
    };
  }, []);
  
  return <>
    <fl-input
      {...props}
      ref={ceInstance}
    >
      {props.Prefix && <div slot="prefix">{props.Prefix}</div>}
      {props.Suffix && <div slot="suffix">{props.Suffix}</div>}
    </fl-input>
  </>
}) as any as FC<PropsTypeReact>

// src/components/scroll/wrap.vue2.vue
<template>
  <fl-scroll
    v-bind="$props"
    @update-model-value="$emit('update:modelValue', $event.detail[0])"
    ref="ceInstance"
  >
    <slot></slot>
  </fl-scroll>
</template>
<script>
import './index';

export default {
  components:{},
  props: {
    modelValue: {
      type: [String, Number],
      required: true
    },
  },
  data() {
    return {
      type: 'danger'
    }
  },
  mounted() {
    this.$refs['ceInstance']?._onMounted?.();
  },
  methods: {

  },
}
</script>
<style lang="scss" scoped>

</style>
