// src/components/paging-select/wrap.vue3.vue
<template>
  <div>
    <h1>fl-paging-select for vue3</h1>
    <fl-paging-select
      ref="compRef"
      :api="props.api"
      :requestParams="props.requestParams"
      :optionSetting="props.optionSetting"
      v-bind="otherProps"
    ></fl-paging-select>
  </div>
</template>

<script lang="ts" setup>
import { ref, computed, onMounted, useAttrs } from 'vue';
import './index';

const props = defineProps({
  api: {
    type: Function,
    required: true,
  },
  requestParams: {
    type: Object,
    default: () => ({})
  },
  /** 选项数据配置项 */
  optionSetting: {
    type: Object,
    default: () => ({})
  },
})

const otherProps = useAttrs();

const compRef = ref();

onMounted(()=>{
  compRef.value?._onMounted?.();
})

defineExpose({
  
})
</script>

<style lang="scss" scoped>

</style>

// src/components/paging-select/wrap.react.tsx
import { useEffect, useRef } from 'react';
import './index';

export default function FlPagingSelect(props: {
  id: string
  label: string
  api: Function
  immediate?: boolean
  optionSetting: {
    label: string
    id: string
  }
}) {
  const pagingSelectRef = useRef();
  useEffect(() => {
    pagingSelectRef.current.api = props.api;
  }, [props.api])
  useEffect(() => {
    pagingSelectRef.current.optionSetting = props.optionSetting;
  }, [props.optionSetting])
  useEffect(() => {
    pagingSelectRef.current.id = props.id;
  }, [props.id])
  useEffect(() => {
    pagingSelectRef.current.immediate = props.immediate;
  }, [props.immediate])
  useEffect(() => {
    pagingSelectRef.current._onMounted?.();
  }, [])

  return <>
    <fl-paging-select
      ref={pagingSelectRef}
      label={props.label}
      {...props}
      style={{ width: '300px' }}
    >
    </fl-paging-select>
  </>
}
